UPDATE mysql.user SET Password=PASSWORD('${MYSQL_ROOT_PASSWD}') WHERE User='root';
DROP USER '';
DELETE FROM mysql.db WHERE Db LIKE 'test%';
CREATE DATABASE ${DATABASE_NAME};
GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'%' IDENTIFIED BY '${DATABASE_PASSWORD}';
GRANT CREATE, CREATE USER, GRANT OPTION, SHOW DATABASES ON *.* TO '${DATABASE_USER}'@'%';
FLUSH PRIVILEGES;